### PR TITLE
fix: don't die in browsers that do not support shadow DOM. Fixes #255.

### LINKED ISSUE #255: 2.10.0: error in Phantom on `content` elements
When running `2.10.0` in PhantomJS `1.9.18` on pages with `<content>` elements sometimes this error occurs:

```
TypeError: 'undefined' is not a function (evaluating 'e.getDistributedNodes()')
```

it seems as if this method is not available.
The markup in question looks like this:

``` html
<section class="aui-page-panel-content">
    <content tag="selectedWebItem" hidden="">applinks-configure-application-links</content>
    <content tag="bodyClass" hidden="">applinks-page</content>
</section>
```

The native implementation of that method seems not available in Phantom:

``` console
phantomjs> document.createElement('content').getDistributedNodes
undefined
```

~~But I couldn't find out whether that finding is correct or not. Can anyone shed some light on this?~~ And if it is not available, my recommendation would be make changes to axs to degrade silently and just ignore any distributed nodes.

### PR DESCRIPTION
**Pull request by joscha**
Some browser supported don't support Shadow DOM. However the DOMUtils expect this. Fixes #255.

### CODE REVIEW

**Comment by joscha** [comment]
is there anything else that needs to be done to get this PR integrated? Any missing information?

**Comment by joscha** [comment]
any chance to get this merged?

**Comment by addyosmani** [comment]
We may want to review the need for this change given any updates to ShadowDOM specs for V1. I'll need to take another look at the original issue.

**Comment by joscha** [comment]
@addyosmani is there anything I can do to get this merged?

**Pull request merged**
