### PR TITLE
+ Selenium WebDriver example (scala)

### PR DESCRIPTION
**Pull request by kristapsmelderis**
Wrote code example on how to run the audit javascript via Selenium WebDriver JavascriptExecutor.
+ Some bits about caching for common sense.

### CODE REVIEW

**Comment by Ragnijs** [comment]
I signed it!

**Comment by alice** [comment]
Thanks for the PR, and sorry for taking so long to get back to you!

Would you be able to split out the new audit rule into its own PR, and add a test for it?

**Comment by kristapsmelderis** [comment]
Hi,
I'm new to accessibility testing area, so the terminology is 'new' to me.

I wanted to add details to Readme file only (with this Pull Request).

Are you talking about the test I added to my Forked project ? (I am unsure if that particular test is even valid for the original project, it was just a practice, to see how to extend the existing project with new tests).

**Comment by alice** [comment]
Right, this pull request contains FirstHeadingIsNotH1.js which is a new audit rule.

If you don't want to include it in this pull request (which it sounds like you don't), you should revert it in the branch you're requesting us to pull (master).

Alternatively, what many people do is create a new branch specifically for their pull request. You could create a new branch from master, revert FirstHeadingIsNotH1.js there, and then close this PR and open a new one from the branch.

**Comment by kristapsmelderis** [comment]
Hi,
I was not familiar with how smart GitHub is. Thought that Pull Request isolates itself but turns out whatever I add in future just sticks to the same PR.
I did:
git reset --soft HEAD^
git push origin +master
...on my forked project. My PR now does not contain the new audit rule.

Is there a google hangout with people that take care of this project ?

**Comment by alice** [comment]
Right, anything you commit to the same branch will become part of the same pull request. This is useful when, for example, you get a comment on your PR that requires you to change something in your code: you can make the change in your branch and push it, and it shows up in the PR.

For this reason, I make branches for all of my changes, and keep master as a clean copy of origin/master. It really makes this whole workflow much simpler, and GitHub really encourages this flow: if you push a new branch to your repository, it'll ask if you want to create a pull request, and once the PR is merged it'll ask if you want to delete the branch.

There's no google hangout, but you might want to jump on the web-a11y Slack via web-a11y.herokuapp.com - you can find me and @ckundo there.

**Pull request merged**
