### PR TITLE
fix: `isLargeFont` should not die on documents without body

### PR DESCRIPTION
**Pull request by joscha**
In some rare cases `document.body` is not defined. In these cases the `isLargeFont` method dies due to 

```
TypeError: 'null' is not an object (evaluating 'window.getComputedStyle(document.body, null).fontSize')
```

This PR fixes this and adds one test for `isLargeFont` (was added to make sure there is no regression)

### CODE REVIEW

**Comment by joscha** [comment]
any chance to get this merged?

**Comment by addyosmani** [comment]
> In some rare cases document.body is not defined

Can you share an example of where you were running into this? The change itself looks fine to me, but curious about the necessity for the fix.

**Comment by joscha** [comment]
hi @addyosmani - it's for websites that do not have a `<body>` element. Not saying they are sane websites, but they do exist and trip up the a11y developer tools :)

**Comment by joscha** [comment]
@addyosmani is there anything I can do to get this merged?

**Comment by addyosmani** [comment]
Now that we've merged in your other PR, we'll need this one to be rebased I'm afraid. Also sorry for the long time waiting on getting these reviewed and merged. Github notifications have been failing me lately :/

**Comment by joscha** [comment]
no worries - resolved the conflicts, should be gtg @addyosmani

**Comment by joscha** [comment]
Did this end up getting integrated @addyosmani?

**Pull request closed without merging**
