### PR TITLE
Fix table audits

### PR DESCRIPTION
**Pull request by joscha**
This pull request fixes two things regarding table auditing:
1. The table checks never ran, they were forgotten in the QUnit HTML :warning:. This is fixed in 9095d4f.
2. The table checks failed with an `'undefined' is not an object (evaluating 'headerRow.children')` on some pages. This is due to the fact that the auditor assumes a complete table. If the markup is broken however, let's say an empty `<table></table>` without a single `<tr>` then there are no rows. This is fixed via 4f899db.

### CODE REVIEW

**Comment by joscha** [comment]
is there anything else that needs to be done to get this PR integrated? Any missing information?

**Comment by joscha** [comment]
any chance to get this merged?

**Comment by addyosmani** [comment]
@joscha I'm going to step in to try helping review some of the backlog here. Sorry for the delays in some of these PRs getting reviewed. Hoping to get to this either before or after the next release is tagged.

**Comment by addyosmani** [comment]
..and, thanks for all your other PRs! 🍰

**Comment by joscha** [comment]
I can rebase it if that helps @addyosmani

**Comment by joscha** [comment]
@addyosmani is there anything I can do to get this merged?

**Comment by joscha** [comment]
Did this end up getting integrated @addyosmani?

**Pull request closed without merging**
