### PR TITLE
Release

### PR DESCRIPTION
**Pull request by alice**

### CODE REVIEW

**Comment by jdan** [comment]
Will this be published to NPM?

**Comment by alice** [comment]
@addyosmani has been doing the NPM pushes (I think?) - he should know (and I should probably start doing them at the same time as I do releases).

**Comment by addyosmani** [comment]
Sorry for the delay! I've just published the latest stable and RC release (for anyone that manually opts into that) to npm, directly from the current tags.

**Comment by jdan** [comment]
@addyosmani thanks!

**Pull request merged**
