### PR TITLE
accessibility-developer-tools

### PR DESCRIPTION
**Pull request by VTG38**

### CODE REVIEW

**Comment by bridgetinvt** [comment]
( I signed It!)

**Comment by bridgetinvt** [comment]
FYI
I signed it!

---

Review status: 0 of 97 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322#-:-KYd_9aIHZfB0VUj9mYp:b-qbmfp4)*

**Comment by bridgetinvt** [comment]
Reviewed 97 of 97 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322)*

**Comment by bridgetinvt** [comment]
*[package.json, line 3 at r1](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322#-KYe8aiYNCjuLR1lpEGx:-KYe8aiYNCjuLR1lpEGy:b-5x5kad) ([raw file](https://github.com/googlechrome/accessibility-developer-tools/blob/322ca06fa1b4b012d1a61b87f63bfa6581a67c41/package.json#L3)):*
>   "version": "2.11.0",

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322)*

**Comment by bridgetinvt** [comment]
*[package.json, line 9 at r1](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322#-KYe8irOhaQblkGjSvrd:-KYe8irOhaQblkGjSvre:bbzo02e) ([raw file](https://github.com/googlechrome/accessibility-developer-tools/blob/322ca06fa1b4b012d1a61b87f63bfa6581a67c41/package.json#L9)):*
> "grunt": "^0.4.5"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322)*

**Comment by bridgetinvt** [comment]
*[package.json, line 9 at r1](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322#-KYe8irOhaQblkGjSvrd:-KYe9L8BfbcGNGiT7E70:b2ni9ah) ([raw file](https://github.com/googlechrome/accessibility-developer-tools/blob/322ca06fa1b4b012d1a61b87f63bfa6581a67c41/package.json#L9)):*
<details><summary><i>Previously, bridgetinvt (VTG38) wrote…</i></summary><blockquote>

> "grunt": "^0.4.5"
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322)*

**Comment by bridgetinvt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322#-KYe8aiYNCjuLR1lpEGx:-KYe9dYp3ZywiMje4I5C:b-896fix) ([raw file](https://github.com/googlechrome/accessibility-developer-tools/blob/322ca06fa1b4b012d1a61b87f63bfa6581a67c41/package.json#L3)):*
<details><summary><i>Previously, bridgetinvt (VTG38) wrote…</i></summary><blockquote>

>   "version": "2.11.0",
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/googlechrome/accessibility-developer-tools/322)*

**Comment by VTG38** [comment]
Confirm

**Pull request closed without merging**
